var o=null;function r(b){return function(){return b}}
(function(b){function h(a,e,c,d,f){d=d||document;this.requested=a;this.onSuccess=e||m;this.onError=c||m;this.doc=d;this.writeSync=this.inHead=f||d.readyState!="complete";this.id=q++;i[this.id]=this}function g(a,e,c,d,f,b,h){this.featureName=a;this.name=e;this.loadPath=c;this.detector=d||m;this.dependencies=f;this.charset=b||"utf-8";this.loadCallback=h;this.readyState="uninitialized"}function n(a){var a=a||m,e={},c,d,f;for(d in k)if(k.hasOwnProperty(d)){c=[];for(f=0;f<k[d].length;f++)a(k[d][f])&&c.push(k[d][f].name);
c.length>0&&(e[d]=c)}return e}function j(a,e){var c;if(!e||e==="auto")a:{for(var d=(c=k[a])?c.length:0,f=d;d--;)if(c[d].readyState==="complete"||c[d].readyState==="loading"){c=c[d];break a}for(d=0;d<f;d++)if(c[d].detector()){c=c[d];break a}c=o}else c=e==="none"?o:p(a,e);return c}function p(a,e){for(var c=k[a],d=c?c.length:0;d--;)if(c[d].name===e)return c[d];throw"unknown:[$1]".replace("$1",a+":"+e);}function s(){for(var a in i)i.hasOwnProperty(a)&&i[a]&&!i[a].cancelled&&i[a].load()}function m(){return!0}
var k={},i={},l=function(a){for(var a=a.split("."),e=window,c=a[0]==="window"?1:0;c<a.length;c++)e=e[a[c]]||(e[a[c]]={});return e}(b),q=0;g.prototype={onWrite:function(a){this.readyState="loading";a&&s()},onLoad:function(a){a&&this.onWrite(a);this.readyState="complete";s()},canLoad:function(a,e){for(var c=this.dependencies,d=c?c.length:0,f;d--;){if(a[c[d]]==="none")throw"conflict:[$1]->[$2]".replace("$1",this.featureName).replace("$2",c[d]);f=j(c[d],a[c[d]]||"auto");if(f.readyState==="uninitialized"||
!e&&f.readyState==="loading")return!1}return!0},onLoadCallback:function(a){this.loadCallback&&this.loadCallback();(a=a.getElementById("_onLoad"+this.featureName+"_"+this.name))&&a.parentNode&&a.parentNode.removeChild(a)},writeSync:function(a,e){this.readyState="loading";a.write('<script type="text/javascript" charset="$ENC$" src="$SRC$"><\/script>'.replace("$SRC$",this.loadPath).replace("$ENC$",this.charset));this.loadCallback&&a.write('<script id="$ID$" type="text/javascript" charset="utf-8">$CONTENT$<\/script>'.replace("$ID$",
"_onLoad"+this.featureName+"_"+this.name).replace("$CONTENT$",b+".get('"+this.featureName+"','"+this.name+"').onLoadCallback("+b+".loaders["+e+"].doc)"));this.onLoad(!0)},writeAsync:function(a,e,c){this.readyState="loading";var d=this,f=a.createElement("script");e&&(f.async=!1);f.type="text/javascript";f.charset=this.charset;f.onload=f.onreadystatechange=function(){var c=f.readyState;if(!c||/^(?:loaded|complete)$/i.test(c))f.onload=f.onreadystatechange=o,d.onLoadCallback&&d.onLoadCallback(a),d.onLoad(e)};
f.onerror=function(a){c(a)};f.src=this.loadPath;a.getElementsByTagName("head")[0].appendChild(f);this.onWrite(e)}};g.prototype.featureName=o;g.prototype.onLoadCallback=g.prototype.onLoadCallback;g.prototype.readyState=o;h.prototype={onFinished:function(a){delete i[this.id];jsapi.packages.loadedPackages=l.getLoadedMap();if(a)this.onError(a);else this.onSuccess();(a=this.doc.getElementById("_onSuccess"+this.id))&&a.parentNode&&a.parentNode.removeChild(a)},load:function(){var a=this.requested,e,c,d=
!0,f=this;try{for(c in a)(e=j(c,a[c]))&&this.loadSingle(e,a,this.inHead,this.writeSync,function(a){f.onFinished(a)})&&(d=!1);d&&this.onDone()}catch(b){this.onFinished(b),this.onFinished=m}},onDone:function(){if(!this.done){var a=this;this.inHead?document.write('<script id="$ID$" type="text/javascript" charset="utf-8">$CONTENT$<\/script>'.replace("$ID$","_onSuccess"+a.id).replace("$CONTENT$",b+".loaders["+a.id+"].onFinished();")):window.setTimeout(function(){a.onFinished()},1);this.done=!0}},loadSingle:function(a,
e,c,d,f){if(a.readyState==="complete")return!1;else if(a.readyState==="loading")return!0;var b,h;if(a.canLoad(e,d))c?a.writeSync(this.doc,this.id):a.writeAsync(this.doc,d,f);else{a=a.dependencies;for(b=a.length;b--;)h=j(a[b],e[a[b]]||"auto"),this.loadSingle(h,e,c,d,f)}return!0}};h.prototype.onFinished=h.prototype.onFinished;h.prototype.id=o;h.prototype.doc=o;l.loaders=i;l.features=k;l._detectors={};l.get=j;l.add=function(a,e,c,d,f,b,h){(k[a]||(k[a]=[])).push(new g(a,e,c,d,f,h,b))};l.isLoaded=function(a,
e){return p(a,e).readyState==="complete"};l.load=function(a,e,c,d,b){(new h(a,e,c,d,b)).load()};l.getFeatureMap=function(){return n(function(a){return a.featureName!="base"})};l.getLoadedMap=function(){return n(function(a){return a.featureName!="base"&&a.readyState==="complete"})}})("jsapi.Features");jsapi.Features._detectors["ui-navteq_web"]=r(!0);jsapi.Features._detectors["advsearch-navteq"]=r(!0);jsapi.Features._detectors["search-navteq"]=r(!0);jsapi.Features._detectors["advrouting-navteq"]=r(!0);
jsapi.Features._detectors["routing-navteq"]=r(!0);jsapi.Features._detectors["positioning-w3c"]=function(){var b=!1;try{b=!(!navigator||!(navigator.geolocation&&typeof navigator.geolocation.getCurrentPosition==="function"))}catch(h){}return b};jsapi.Features._detectors["detect-js-p2d-canvas"]=function(){var b=document.createElement("canvas");return!(!b.getContext||!b.getContext("2d"))};jsapi.Features._detectors["map-js-p2d-dom"]=r(!0);
jsapi.Features._detectors["gfx-vml"]=function(){return!document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1")};jsapi.Features._detectors["gfx-svg"]=function(){return document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1")};jsapi.Features._detectors["gfx-canvas"]=function(){var b=document.createElement("canvas");if(!b||!b.getContext)return!1;return typeof b.getContext("2d").fillText==="function"};
jsapi.Features._detectors["kml-kml"]=r(!0);
(function(b){b.packages={availablePackages:jsapi.Features.getFeatureMap(),loadedPackages:{},a:o,isEnvCapable:function(b,g){return jsapi.Features.get(b,g).detector()},isLoaded:function(b,g){return jsapi.Features.isLoaded(b,g)},load:function(b,g,n){var j={};b==="language"?(jsapi.util.ApplicationContext.set("defaultLanguage",g),n&&n()):(j[b]=g,jsapi.Features.load(j,n))},loadAll:function(b,g){var n,j;if(j=b.language)delete b.language,n=function(){jsapi.util.ApplicationContext.set("defaultLanguage",j);
g&&g()};jsapi.Features.load(b,n||g)},register:function(b,g){jsapi.Features.get(b,g).readyState="complete"},init:function(){}}})(jsapi);this.jsapi=this.jsapi||{};this.jsapi.build="jsapi-1.0.13-Bianca-20110824-w34-r10496";
this.jsapi.config={packages:{search:[{name:"navteq"}],advsearch:[{name:"navteq",dependencies:["search"]}],routing:[{name:"navteq"}],advrouting:[{name:"navteq",dependencies:["routing"]}],positioning:[{name:"w3c"}],map:[{name:"js-p2d-dom",dependencies:["gfx"]},{name:"js-p2d-canvas",dependencies:["gfx"]}],gfx:[{name:"canvas"},{name:"svg"},{name:"vml"}],ui:[{name:"navteq_web"}],language:[{name:"en-US"},{name:"de-DE"},{name:"bg-BG"},{name:"es-ES"},{name:"fr-FR"},{name:"it-IT"},{name:"nl-NL"},{name:"zh-CN"},
{name:"zh-HK"},{name:"zh-TW"}],kml:[{name:"kml"}]},assetsPath:"assets/navteq",termsOfUseUrl:"http://jsapi.lbsp.navteq.com/v1/toc.html",tileProviders:"jsapi.map.js.navteqTileProviders"};jsapi.config=this.jsapi.config;
(function(b){function h(a){l=a.dependencies||[];l.push("base");k=key+"-"+a.name;q.add(key,a.name,j+k+".js",q._detectors[k],l)}function g(a){for(var c=/([\\?&]([^=]+)=([^&#]+))/g,d,b={};d=c.exec(a);)b[d[2]]=d[3];return b}function n(){if(s["jsl.js"])return s["jsl.js"];for(var a="jsl.js".replace(".","\\."),c=document.getElementsByTagName("script"),b=c.length,a=RegExp("^(.*\\/"+a+".*|"+a+".*)");b--;)if(a.test(c[b].src))return s["jsl.js"]=c[b].src,s["jsl.js"];throw"InternalError: could not locate jsl.js in the environment.";
}var j,p,s={};if(!b.assetsPath)throw"Internal Error: no asset path has been specified";j=b.loadPath||function(a){a=a.split("/").slice(0,-1);return a.join("/")+(a.length>0?"/":"")}(n());p=b.params||g(n());var m,k,i,l,q=jsapi.Features,a=this;for(key in b.packages){m=b.packages[key];for(i=0;i<m.length;i++)h(m[i]);key!="language"&&!p[key]&&(p[key]="auto")}if(b.addons)for(key in b.addons){m=b.addons[key];for(i=0;i<m.length;i++)h(m[i])}jsapi.packages.availablePackages=q.getFeatureMap();q.add("base","noovi",
j+"base_noovi.js",function(){return a.ovi&&a.ovi.win});q.add("base","withovi",j+"base.js",function(){return!a.ovi||!a.ovi.win});b.params=p;b.baseUrl=j;p.blank||q.load(p,o,function(a){throw a;},o,!0)})(this.jsapi.config);
